export const REQUEST_POSTS = 'REQUEST_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
//export const SELECT_SUBREDDIT = 'SELECT_SUBREDDIT';
// export const INVALIDATE_SUBREDDIT = 'INVALIDATE_SUBREDDIT';
export const ADD_BET = 'ADD_BET';
export const FILTER_BY = 'FILTER_BY';
export const CLEAR_BETSLIP = 'CLEAR_BETSLIP';
export const UPDATE_BETSLIP = 'UPDATE_BETSLIP';
export const REMOVE_BET = 'REMOVE_BET';
export const CHANGE_DEC_FORMAT ='CHANGE_DEC_FORMAT';
export const TOGGLE_MENU ='TOGGLE_MENU';

export const PUSHING_BETS='PUSHING_BETS';

export const RECEIVE_RECEIPT='RECEIVE_RECEIPT';


export const PROMPT_ERROR='PROMPT_ERROR';